const REPETIDOS = {
	"id.is": {
		trim: true,
		optional: true,
		isNumeric: true,
		toInt: true,
		errorMessage: "",
	},
	"name.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"name.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"name.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"name.is": { trim: true, optional: true, isString: true, errorMessage: "" },
	"name.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"name.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"email.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"email.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"email.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"email.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"email.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"email.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"active.is": {
		trim: true,
		optional: true,
		isBoolean: true,
		toBoolean: true,
		errorMessage: "",
	},
	"project.name.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.name.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.name.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.name.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.name.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.name.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.description.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.description.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.description.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.description.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.description.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.description.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"project.createdAt.is": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"project.createdAt.is_not": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"project.createdAt.less_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"project.createdAt.less_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"project.createdAt.more_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"project.createdAt.more_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.id.is": {
		trim: true,
		optional: true,
		isNumeric: true,
		toInt: true,
		errorMessage: "",
	},
	"event.name.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"event.name.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"event.name.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"event.name.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"event.name.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"event.name.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"event.start_date.is": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.start_date.is_not": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.start_date.less_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.start_date.less_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.start_date.more_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.start_date.more_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.end_date.is": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.end_date.is_not": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.end_date.less_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.end_date.less_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.end_date.more_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"event.end_date.more_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"clothe_size.shirt.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shirt.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shirt.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shirt.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shirt.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shirt.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.pants.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.pants.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.pants.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.pants.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.pants.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.pants.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.jacket.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.jacket.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.jacket.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.jacket.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.jacket.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.jacket.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shoes.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shoes.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shoes.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shoes.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shoes.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"clothe_size.shoes.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.identification_number.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.identification_number.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.identification_number.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.identification_number.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.identification_number.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.identification_number.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.passport_number.begins_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.passport_number.contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.passport_number.ends_with": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.passport_number.is": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.passport_number.is_not": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.passport_number.not_contains": {
		trim: true,
		optional: true,
		isString: true,
		errorMessage: "",
	},
	"personal_info.passport_issuance_date.is": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_issuance_date.is_not": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_issuance_date.less_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_issuance_date.less_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_issuance_date.more_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_issuance_date.more_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_expiration_date.is": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_expiration_date.is_not": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_expiration_date.less_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_expiration_date.less_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_expiration_date.more_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.passport_expiration_date.more_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.birthdate.is": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.birthdate.is_not": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.birthdate.less_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.birthdate.less_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.birthdate.more_than": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
	"personal_info.birthdate.more_than_or_equal": {
		trim: true,
		optional: true,
		isDate: true,
		errorMessage: "",
	},
};
